### ISSUE TITLE
Unable to replicate the reported numbers on CoNLL dataset

### ISSUE THREAD

**Issue by shramesh** [jiesutd/PyTorchSeqLabel#1]
After 100 epochs on the train-dev-test splits of CoNLL 2003, dataset with LSTM and CNN character features, I get the following results for the best dev f-score:

- **LSTM**
**Dev:** time: 5.59s, speed: 627.24st/s; acc: 0.9891, p: 0.9460, r: 0.9465, **f: 0.9463**
Exceed previous best f score: 0.945258548088
**Test:** time: 5.57s, speed: 712.46st/s; acc: 0.9808, p: 0.9102, r: 0.9107, **f: 0.9104**
- **CNN**
**Dev:** time: 5.32s, speed: 660.84st/s; acc: 0.9891, p: 0.9458, r: 0.9460, **f: 0.9459**
Exceed previous best f score: 0.945809491754
**Test:** time: 4.88s, speed: 788.98st/s; acc: 0.9804, p: 0.9081, r: 0.9068, **f: 0.9074**

I'm trying to understand what it takes to reproduce the reported numbers, and also use as a baseline for my experiments. Let me know what are the other parameters that I need to change.  

Also, thanks for open-sourcing the code!

**Comment by jiesutd** [comment]
Hi, I am guessing which kind of tag scheme do you use? Generally BIOES gives better results than BIO.

**Comment by shramesh** [comment]
So, the results that you reported was run with the tag scheme of BIOES?

**Comment by jiesutd** [comment]
Exactly! Welcome to report your new results with bioes tag.

**Comment by udion** [comment]
Are you sure you presented number with BIOES tagscheme?
for BIOES will you be using `get_ner_BMES()` or `get_ner_BIO()` ?

**Comment by jiesutd** [comment]
@udion your data format is neither BIO nor BIOES. 
You use the wrong data format. 
The code is correct, stop yelling the wrong "mistake" you found, which is due to your wrong data input.

**Comment by udion** [comment]
@jiesutd yes, sorry my bad.
I didn't go through the whole data file, a few initial examples seemed to be in the correct format (as there were no multiple tags from same class right next to each other). Later on I realized the example of #23 is actually the **faulty** format (most likely IOB)

P.S. sorry for panicking, awesome repo <3
