### ISSUE TITLE
请问大佬的代码有参考哪些开源项目吗？

### ISSUE THREAD

**Issue by liu-nlper** [jiesutd/PyTorchSeqLabel#2]

**Comment by jiesutd** [comment]
1.官方tutorial中的LSTM-CRF:http://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html
2.https://github.com/LiyuanLucasLiu/LM-LSTM-CRF
3. 还有一些其他PyTorch的lstm-crf的，不过忘了地址了
