### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by LearningPytorch** [jiesutd/PyTorchSeqLabel#5]
Hi, for NER what's the format of the file that the script expects:

```
AL-AIN NNP I-NP I-LOC
, , O O
United NNP I-NP I-LOC
Arab NNP I-NP I-LOC
Emirates NNPS I-NP I-LOC
1996-12-06 CD I-NP O
....
```
like the above? I saw that you need some .bme files.

**Comment by jiesutd** [comment]
Yes, data format follows CoNLL 2003 as you posted. The begin of entity should be B-XXX, where XXX is entity type.

Bmes means BIOES tag scheme, you can also use BIO scheme, both can be supported.

**Comment by LearningPytorch** [comment]
Interesting but I'm getting this
```
Epoch: 43 training finished. Time: 106.94s, speed: 140.13st/s,  total loss: 1227.02264404
gold_num =  4  pred_num =  2  right_num =  2
Dev: time: 7.25s, speed: 481.07st/s; acc: 0.9800, p: 1.0000, r: 0.5000, f: 0.6667
gold_num =  20  pred_num =  2  right_num =  0
Test: time: 6.90s, speed: 536.89st/s; acc: 0.9671, p: 0.0000, r: 0.0000, f: -1.0000
```

**Comment by jiesutd** [comment]
The gold num is only 4, I am sure your data format is incorrect. Please use BIO or BIOES format. The example you post is incorrect, it doesn’t use B-XXX

**Comment by udion** [comment]
Oh, **B-** is compulsory ? I found CoNLL-2003 dataset where there are sentences without **B-** but have **I-** and ** O **

**Comment by udion** [comment]
@jiesutd  no I think you're wrong, we can have examples without **B-** tags, check out the official [CoNLL-2003 documentation](https://www.clips.uantwerpen.be/conll2003/ner/).

It says that **B-** tag is used only if multiple similar tags follow right after each other then first one will be tagged as **B-XXX**

**Comment by udion** [comment]
@LearningPytorch were you able to resolve issue?
